"""add subject to mail_templates

Revision ID: 922959701a11
Revises: 941b3a34c563
Create Date: 2026-01-01 22:16:55.125908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922959701a11'
down_revision = '941b3a34c563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_templates', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
