"""create mail_templates table

Revision ID: 941b3a34c563
Revises: 20260101_04_remove_duration_from_appointment_type
Create Date: 2026-01-01 22:02:31.801137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941b3a34c563'
down_revision = '20260101_04_remove_duration_from_appointment_type'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_templates')
    op.drop_table('mail_signatures')
    # ### end Alembic commands ###
