"""add google_agenda_url to settings

Revision ID: d08867f4fa63
Revises: a388ac6bef2e
Create Date: 2026-01-01 18:17:11.169214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08867f4fa63'
down_revision = 'a388ac6bef2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_agenda_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('google_agenda_url')

    # ### end Alembic commands ###
